version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: my-pick-mysql-prod
    restart: unless-stopped
    volumes:
      - ./data/mysqldata:/var/lib/mysql
    command:
      - --bind-address=0.0.0.0
    ports: []
    env_file:
      - ./envs/.env.prod
    environment:
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
      - MYSQL_TIMEZONE=Asia/Seoul
      - TZ=Asia/Seoul
    networks:
      - my-pick-network

  redis:
    image: redis:alpine
    container_name: my-pick-redis-prod
    restart: unless-stopped
    volumes:
      - ./data/redisdata:/data
    env_file:
      - ./envs/.env.prod
    ports: []
    depends_on:
      - mysql
    networks:
      - my-pick-network

  server:
    image: krgeobuk/my-pick-server:prod
    container_name: my-pick-server-prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./logs:/app/logs
    ports: []
    env_file:
      - ./envs/.env.prod
    environment:
      - TZ=Asia/Seoul
    networks:
      - my-pick-network
      - msa-network
    depends_on:
      - redis
      - mysql

networks:
  my-pick-network:
    driver: bridge
  msa-network:
    external: true
  shared-network:
    external: true
